export type Poem = {
  slug: string;
  n: string;
  lang: "id" | "en";
  title: string;
  theme: string;
  lines: string[];
};

export const POEMS: Poem[] = [
  {
    slug: "orang-di-balik-orangnya",
    n: "I",
    lang: "id",
    title: "Orang di Balik Orangnya",
    theme: "Orang yang ada di balik orang yang dilihat semua orang",
    lines: [
      "Chalika Azka Feirazy,",
      "di ruangan yang penuh, kamu selalu jadi yang paling terdengar,",
      "dan aku selalu penasaran siapa yang menjaga pintunya",
      "ketika semua orang sudah pulang.",
      "",
      "Ada kamu yang tertawa lebih dulu supaya tidak ada yang canggung.",
      "Ada kamu yang mengetik lalu menghapus,",
      "mengetik lagi, menghapus lagi,",
      "sampai kalimatnya cukup kecil untuk tidak merepotkan siapa pun.",
      "",
      "Orang mengira kamu terbuka",
      "karena kamu mudah bicara.",
      "Padahal bicara itu halaman depan;",
      "kamarnya ada di belakang,",
      "dan kuncinya kamu simpan sendiri.",
      "",
      "Aku tidak sedang meminta kuncinya.",
      "Aku cuma ingin kamu tahu",
      "bahwa aku tahu kamarnya ada,",
      "dan aku tidak menganggapnya kelemahan.",
      "",
      "Yang paling ramai di meja",
      "kadang yang paling sepi di perjalanan pulang.",
      "Dan kalau suatu hari kamu capek menjaga pintu itu,",
      "aku bisa duduk di depannya sebentar.",
      "Tidak untuk masuk.",
      "Hanya supaya tidak ada yang menunggu sendirian.",
    ],
  },
  {
    slug: "hal-hal-kecil-yang-tidak-kamu-hitung",
    n: "II",
    lang: "id",
    title: "Hal-hal Kecil yang Tidak Kamu Hitung",
    theme: "Hal kecil yang dia lakukan tanpa sadar itu penting",
    lines: [
      "Kamu mengirim pesan jam satu pagi",
      "untuk menanyakan kabar orang yang kemarin murung,",
      "lalu besoknya kamu bilang, ah, itu bukan apa-apa.",
      "",
      "Kamu ingat nama tokoh di buku yang aku sebut sekali,",
      "ingat minuman yang tidak jadi aku pesan,",
      "ingat kalimat yang membuatku diam bulan lalu.",
      "Kamu simpan semuanya",
      "seperti orang menyimpan struk belanja",
      "yang ternyata jadi bukti bahwa hari itu benar-benar terjadi.",
      "",
      "Kamu memilih tempat makan yang bukan maumu",
      "dan berkata tidak apa-apa, aku ikut saja,",
      "setengah detik setelah wajahmu sempat memilih sesuatu yang lain.",
      "Aku melihat setengah detik itu, Chalika Azka Feirazy.",
      "Aku selalu melihatnya.",
      "",
      "Bagimu itu semua bukan pekerjaan.",
      "Bagimu itu cuma cara hidup, cuma refleks, cuma sopan.",
      "Tapi coba hitung ulang:",
      "berapa banyak orang yang kamu buat merasa penting",
      "hanya karena kamu tidak lupa.",
      "",
      "Kalau ada neraca untuk hal semacam ini,",
      "kamu sudah lama menabung",
      "di rekening yang tidak pernah kamu buka.",
      "",
      "Suatu hari, tolong ambil sedikit untuk dirimu sendiri.",
      "Bukan karena sudah pantas.",
      "Karena memang punyamu dari dulu.",
    ],
  },
  {
    slug: "belajar-pulang-ke-diri-sendiri",
    n: "III",
    lang: "id",
    title: "Belajar Pulang ke Diri Sendiri",
    theme: "Proses belajar mencintai dirinya sendiri yang belum selesai",
    lines: [
      "Ada jarak antara tahu dan melakukan,",
      "dan kamu tinggal di sana lebih lama dari yang kamu akui.",
      "",
      "Di jurnalmu, kamu jelas.",
      "Kamu bisa menulis apa yang salah,",
      "kenapa itu salah,",
      "dan apa yang seharusnya dilakukan besok pagi.",
      "Lalu besok pagi datang",
      "dan kamu memilih menyelamatkan orang lain lebih dulu.",
      "",
      "Aku tidak akan bilang itu bodoh.",
      "Itu bukan bodoh.",
      "Itu kebiasaan lama yang dulu pernah menyelamatkanmu,",
      "dan kebiasaan tidak pergi hanya karena kita sudah pintar.",
      "",
      "Belajar mencintai diri sendiri, ternyata,",
      "bukan urusan kalimat afirmasi di depan cermin.",
      "Lebih mirip kerja tukang:",
      "satu paku, satu papan, satu keputusan kecil",
      "yang tidak ada saksinya.",
      "Makan hari ini. Tidur lebih cepat. Bilang tidak.",
      "",
      "Kamu belum selesai.",
      "Aku juga belum.",
      "Tapi aku sudah melihat kamu memperbaiki hal yang sama",
      "dengan cara yang berbeda dari bulan pertama,",
      "dan itu bukan hal kecil, itu bukti.",
      "",
      "Pulanglah pelan-pelan ke dirimu, Chalika Azka Feirazy.",
      "Rumah itu tidak akan marah",
      "karena kamu datang terlambat.",
    ],
  },
  {
    slug: "field-notes-on-a-quiet-face",
    n: "IV",
    lang: "en",
    title: "Field Notes on a Quiet Face",
    theme: "Seeing someone beyond what they show",
    lines: [
      "There is the face you bring to the table",
      "and the face you keep for the walk home,",
      "and I have been slowly learning",
      "that they are the same face in different weather.",
      "",
      "You laugh half a beat early when a subject gets close.",
      "You say it's fine in a lower register than you say anything else.",
      "You answer a hard question by asking me a kinder one.",
      "These are not lies. They are load-bearing.",
      "",
      "So I stopped listening for what you told me",
      "and started listening for where you paused,",
      "the way a person taps a wall",
      "to find out which parts are hollow.",
      "",
      "Chalika Azka Feirazy,",
      "I am not trying to catch you at anything.",
      "There is nothing to catch.",
      "I am only trying to be the kind of person",
      "who does not need the loud version to know something happened.",
      "",
      "You do not have to translate yourself for me.",
      "I am learning the original.",
      "Slowly, badly, with a bad accent,",
      "but every week a little less lost in it.",
    ],
  },
  {
    slug: "in-progress",
    n: "V",
    lang: "en",
    title: "In Progress",
    theme: "Loving someone while knowing they are still becoming",
    lines: [
      "I did not fall for a finished thing.",
      "I want that on the record,",
      "because you keep apologising",
      "for being under construction",
      "as though I arrived expecting a museum.",
      "",
      "I arrived at a workshop.",
      "There was sawdust. There was a wall half-painted",
      "in a colour you were still arguing with.",
      "Somebody had left the lights on all night, working.",
      "It was the most alive room I had been in for a while.",
      "",
      "You will be different in a year.",
      "That is not a risk I tolerate,",
      "it is the part I am here for.",
      "I would rather learn you six times",
      "than memorise you once and be done.",
      "",
      "So take the time. Take the wrong turn.",
      "Repaint the wall. Change the plan in March.",
      "I am not standing here with a stopwatch",
      "waiting for the person you are supposed to become.",
      "",
      "I like the one with the paint on her hands.",
      "I have liked her since the beginning,",
      "and the beginning was only three months ago,",
      "which means I have barely started.",
    ],
  },
  {
    slug: "a-quiet-promise",
    n: "VI",
    lang: "en",
    title: "A Quiet Promise, Not a Vow",
    theme: "A quiet promise to keep discovering her",
    lines: [
      "I will not promise forever.",
      "Forever is a word people use",
      "when they would rather not do the weekly work.",
      "",
      "Here is a smaller promise, and a harder one:",
      "I will keep asking the second question.",
      "I will keep noticing when your sentences get short.",
      "I will keep my tone steady on the days",
      "when my own week has been unkind,",
      "because you should not have to guess",
      "which version of me is walking through the door.",
      "",
      "I will be wrong about you regularly.",
      "I will update instead of defending the old file.",
      "I will let you be a different person in June",
      "than the one described in this document,",
      "and I will not hold the earlier draft against you.",
      "",
      "Chalika Azka Feirazy,",
      "I am not trying to complete the study.",
      "I am trying to stay in the room where it happens,",
      "for as long as you would like me there,",
      "learning a subject that keeps moving",
      "and being glad, every single time, that it does.",
    ],
  },
];

export function poemBySlug(slug: string) {
  return POEMS.find((p) => p.slug === slug);
}
